name: Bug Report
description: Report a bug or issue with Pulse
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened, what you expected to happen, and any relevant details.
    validations:
      required: true

  - type: checkboxes
    id: prechecks
    attributes:
      label: Pre-Submission Checks
      description: Before submitting a bug, make sure you've actually done the following. These are required to help us help you faster.
      options:
        - label: I have **not cloned Pulse from source** (using official builds)
          required: true
        - label: I have searched for existing solutions / issues and couldn't find one
          required: true
        - label: I am using the **latest version** of Pulse
          required: true
        - label: I have **read all pre-checks above** and am submitting this honestly
          required: true
        - label: I understand that submitting false information may slow down bug fixes
          required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        To reproduce issue, look for the error in the devconsole.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Pulse are you using? Find this under Settings (the cog) -> About
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 10, Windows 11
    validations:
      required: true

  - type: file
    id: log_file
    attributes:
      label: Upload Log File
      description: Please upload any relevant log files or error dumps related to this bug.
      placeholder: Choose a file, find it under logs -> latest.log (or the one related to the crash)
      accept: ".log"
      multiple: true
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots, error messages, or logs.
